"""3

Revision ID: 9c44d324bfcf
Revises: 4167dc46a0b0
Create Date: 2021-11-10 19:09:42.020104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c44d324bfcf'
down_revision = '4167dc46a0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
