"""6

Revision ID: 068864593c40
Revises: b92869e77fd5
Create Date: 2021-11-15 21:43:53.973373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068864593c40'
down_revision = 'b92869e77fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
