"""init3

Revision ID: 35827cd1afe4
Revises: 5b7d80adfc1c
Create Date: 2021-07-10 17:58:58.461391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35827cd1afe4'
down_revision = '5b7d80adfc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
