"""init4

Revision ID: 3c047a43d111
Revises: 35827cd1afe4
Create Date: 2021-07-10 18:07:37.470796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c047a43d111'
down_revision = '35827cd1afe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
