"""1

Revision ID: 71128b3821d4
Revises: 
Create Date: 2021-11-05 22:12:45.998409

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '71128b3821d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('chess_variant_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id_while', sa.Integer(), nullable=False),
    sa.Column('user_id_black', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('moves', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_chess_variant_id'), 'game', ['chess_variant_id'], unique=False)
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_index(op.f('ix_game_moves'), 'game', ['moves'], unique=False)
    op.create_index(op.f('ix_game_position'), 'game', ['position'], unique=False)
    op.create_index(op.f('ix_game_status_id'), 'game', ['status_id'], unique=False)
    op.create_index(op.f('ix_game_user_id_black'), 'game', ['user_id_black'], unique=False)
    op.create_index(op.f('ix_game_user_id_while'), 'game', ['user_id_while'], unique=False)

    op.create_table('game_chess_variant',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('chess_variant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_chess_variant_chess_variant'), 'game_chess_variant', ['chess_variant'], unique=False)
    op.create_index(op.f('ix_game_chess_variant_id'), 'game_chess_variant', ['id'], unique=False)

    op.create_table('game_status',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_status_id'), 'game_status', ['id'], unique=False)
    op.create_index(op.f('ix_game_status_status'), 'game_status', ['status'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_group'), 'user', ['group'], unique=False)
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_is_verified'), 'user', ['is_verified'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_is_verified'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.drop_index(op.f('ix_user_group'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_status_status'), table_name='game_status')
    op.drop_index(op.f('ix_game_status_id'), table_name='game_status')
    op.drop_table('game_status')
    op.drop_index(op.f('ix_game_chess_variant_id'), table_name='game_chess_variant')
    op.drop_index(op.f('ix_game_chess_variant_chess_variant'), table_name='game_chess_variant')
    op.drop_table('game_chess_variant')
    op.drop_index(op.f('ix_game_user_id_while'), table_name='game')
    op.drop_index(op.f('ix_game_user_id_black'), table_name='game')
    op.drop_index(op.f('ix_game_status_id'), table_name='game')
    op.drop_index(op.f('ix_game_position'), table_name='game')
    op.drop_index(op.f('ix_game_moves'), table_name='game')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_index(op.f('ix_game_chess_variant_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
