"""5

Revision ID: b92869e77fd5
Revises: 9b27b3b39448
Create Date: 2021-11-15 21:19:15.155638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92869e77fd5'
down_revision = '9b27b3b39448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
