"""init2

Revision ID: ed273659f5a2
Revises: 40f6aa901112
Create Date: 2021-07-11 20:05:51.312113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed273659f5a2'
down_revision = '40f6aa901112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
